DROP TABLE IF EXISTS WORKOUT_EXERCISES;
DROP TABLE IF EXISTS WORKOUTS;
DROP TABLE IF EXISTS EXERCISES;

-- Don't change anything of the Exercises table, nor fields.

CREATE TABLE EXERCISES(
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    SETS_AMOUNT INT,
    REPS INT,
    WEIGHT FLOAT,
    NAME VARCHAR(255)
);

CREATE TABLE WORKOUTS(
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(255),
    DIFFICULTY INT,
    STATUS VARCHAR(255),
    CREATION_DATE DATE
);

CREATE TABLE WORKOUT_EXERCISES(
    WORKOUT_ID BIGINT,
    EXERCISE_ID BIGINT,
    PRIMARY KEY(WORKOUT_ID, EXERCISE_ID),
    FOREIGN KEY(WORKOUT_ID) REFERENCES WORKOUTS(ID),
    FOREIGN KEY(EXERCISE_ID) REFERENCES EXERCISES(ID)
);